version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: Postgresql
    restart: always
    environment:
      POSTGRES_USER: Cloudmarkdown
      POSTGRES_PASSWORD: Cloudmarkdown
      PGPASSWORD: Cloudmarkdown
      POSTGRES_DB: Cloudmarkdown
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./middleware/postgresql/data:/var/lib/postgresql/data
  app:
    container_name: FastAPI
    build: ./middleware/fastapi
    volumes:
      - ./api:/app 
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - "postgres"
  nuxt-app:
    container_name: NodeApp
    build: ./middleware/nuxt
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    working_dir: /app
