version: '3'
services:
  node:
    image: node:14.9.0-alpine3.10
    container_name: node
    volumes:
      - ./app:/app
    tty: true
    ports:
      - 8080:8080
  app:
    container_name: FastAPI
    build: . 
    volumes:
      - ./api:/app 
    ports:
      - "8000:8000"
    command: >
      bash -c "yarn install &&
      yarn run generate -g &&
      cd ./dist && npm run start"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: Cloudmarkdown
      POSTGRES_PASSWORD: Cloudmarkdown
      PGPASSWORD: Cloudmarkdown
      POSTGRES_DB: Cloudmarkdown
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
